---
- name: Converge
  hosts: all
  gather_facts: true
  become: true
  pre_tasks:
    - name: Update cache(apt)
      ansible.builtin.apt:
        update_cache: true
      when: ansible_facts.pkg_mgr == 'apt'
      changed_when: false
    - name: Update cache(dnf)
      ansible.builtin.dnf:
        update_cache: true
      when: ansible_facts.pkg_mgr == 'dnf'
      changed_when: false
  tasks:
    - name: Find variable file
      ansible.builtin.set_fact:
        variable_file: "{{ lookup('first_found', params, errors='ignore') }}"
      vars:
        params:
          files:
            - "{{ lookup('env', 'MOLECULE_SCENARIO_DIRECTORY') }}/group_vars/all.yml"
    - name: Include variable file
      ansible.builtin.include_vars:
        file: "{{ variable_file }}"
      when: variable_file | length > 0
    - name: Include role
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        install_tools:
          - "{{ lookup('env', 'MOLECULE_SCENARIO_DIRECTORY') | basename }}"
