---
- name: Set Install version variable
  when: fd_version == 'latest'
  block:
    - name: Get latest version
      ansible.builtin.include_tasks:
        file: common/get_latest_version.yml
      vars:
        github_repo: "{{ tools_fd_repo }}"
        target_name: fd
    - name: Set package version
      ansible.builtin.set_fact:
        fd_version: "{{ latest_version }}"
- name: Set package file variable
  ansible.builtin.set_fact:
    package_file: fd_{{ fd_version[1:] }}_{{ arch_type_maps[ansible_facts['architecture']] }}.deb
  vars:
    arch_type_maps:
      x86_64: amd64
      aarch64: arm64
- name: Install fd
  ansible.builtin.apt:
    deb: https://github.com/{{ tools_fd_repo }}/releases/download/{{ fd_version }}/{{ package_file }}
