# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'
tasks:
  notify:
    internal: true
    silent: true
    cmds:
      - afplay /System/Library/Sounds/Glass.aiff
  notify:all:
    internal: true
    silent: true
    cmds:
      - afplay /System/Library/Sounds/Hero.aiff
  default:
    desc: Run Molecule tests for default scenario
    cmds:
      - molecule test
      - task: notify
  all:
    desc: Run Molecule tests for all scenario
    cmds:
      - molecule test -s all
      - task: notify
  assh:
    desc: Run Molecule tests for assh scenario
    cmds:
      - molecule test -s assh
      - task: notify
  bat:
    desc: Run Molecule tests for bat scenario
    cmds:
      - molecule test -s bat
      - task: notify
  bottom:
    desc: Run Molecule tests for bat scenario
    cmds:
      - molecule test -s bottom
      - task: notify
  codex:
    desc: Run Molecule tests for codex scenario
    cmds:
      - molecule test -s codex
      - task: notify
  d2:
    desc: Run Molecule tests for d2 scenario
    cmds:
      - molecule test -s d2
      - task: notify
  delta:
    desc: Run Molecule tests for delta scenario
    cmds:
      - molecule test -s delta
      - task: notify
  diff-pdf:
    desc: Run Molecule tests for diff-pdf scenario
    cmds:
      - molecule test -s diff-pdf
      - task: notify
  direnv:
    desc: Run Molecule tests for direnv scenario
    cmds:
      - molecule test -s direnv
      - task: notify
  drawio:
    desc: Run Molecule tests for drawio scenario
    cmds:
      - molecule test -s drawio
      - task: notify
  duckdb:
    desc: Run Molecule tests for duckdb scenario
    cmds:
      - molecule test -s duckdb
      - task: notify
  eza:
    desc: Run Molecule tests for eza scenario
    cmds:
      - molecule test -s eza
      - task: notify
  fd:
    desc: Run Molecule tests for fd scenario
    cmds:
      - molecule test -s fd
      - task: notify
  fnt:
    desc: Run Molecule tests for fnt scenario
    cmds:
      - molecule test -s fnt
      - task: notify
  gitleaks:
    desc: Run Molecule tests for gitleaks scenario
    cmds:
      - molecule test -s gitleaks
      - task: notify
  github-cli:
    desc: Run Molecule tests for github-cli scenario
    cmds:
      - molecule test -s github-cli
      - task: notify
  git-flow:
    desc: Run Molecule tests for git-flow scenario
    cmds:
      - molecule test -s git-flow
      - task: notify
  glow:
    desc: Run Molecule tests for glow scenario
    cmds:
      - molecule test -s glow
      - task: notify
  goaccess:
    desc: Run Molecule tests for goaccess scenario
    cmds:
      - molecule test -s goaccess
      - task: notify
  graphviz:
    desc: Run Molecule tests for graphviz scenario
    cmds:
      - molecule test -s graphviz
      - task: notify
  httpie:
    desc: Run Molecule tests for httpie scenario
    cmds:
      - molecule test -s httpie
      - task: notify
  jc:
    desc: Run Molecule tests for jc scenario
    cmds:
      - molecule test -s jc
      - task: notify
  lazydocker:
    desc: Run Molecule tests for lazydocker scenario
    cmds:
      - molecule test -s lazydocker
      - task: notify
  lazygit:
    desc: Run Molecule tests for lazygit scenario
    cmds:
      - molecule test -s lazygit
      - task: notify
  lnav:
    desc: Run Molecule tests for lnav scenario
    cmds:
      - molecule test -s lnav
      - task: notify
  logdy:
    desc: Run Molecule tests for logdy scenario
    cmds:
      - molecule test -s logdy
      - task: notify
  mecab:
    desc: Run Molecule tests for mecab scenario
    cmds:
      - molecule test -s mecab
      - task: notify
  mermaid-cli:
    desc: Run Molecule tests for mermaid-cli scenario
    cmds:
      - molecule test -s mermaid-cli
      - task: notify
  nkf:
    desc: Run Molecule tests for nkf scenario
    cmds:
      - molecule test -s nkf
      - task: notify
  ni:
    desc: Run Molecule tests for ni scenario
    cmds:
      - molecule test -s ni
      - task: notify
  osv-scanner:
    desc: Run Molecule tests for osv-scanner scenario
    cmds:
      - molecule test -s osv-scanner
      - task: notify
  pandoc:
    desc: Run Molecule tests for pandoc scenario
    cmds:
      - molecule test -s pandoc
      - task: notify
  pict:
    desc: Run Molecule tests for pict scenario
    cmds:
      - molecule test -s pict
      - task: notify
  plantuml:
    desc: Run Molecule tests for plantuml scenario
    cmds:
      - molecule test -s plantuml
      - task: notify
  poppler-utils:
    desc: Run Molecule tests for poppler-utils scenario
    cmds:
      - molecule test -s poppler-utils
      - task: notify
  rclone:
    desc: Run Molecule tests for rclone scenario
    cmds:
      - molecule test -s rclone
      - task: notify
  restic:
    desc: Run Molecule tests for restic scenario
    cmds:
      - molecule test -s restic
      - task: notify
  ripgrep:
    desc: Run Molecule tests for ripgrep scenario
    cmds:
      - molecule test -s ripgrep
      - task: notify
  runn:
    desc: Run Molecule tests for runn scenario
    cmds:
      - molecule test -s runn
      - task: notify
  s3fs:
    desc: Run Molecule tests for s3fs scenario
    cmds:
      - molecule test -s s3fs
      - task: notify
  task:
    desc: Run Molecule tests for task scenario
    cmds:
      - molecule test -s task
      - task: notify
  tbls:
    desc: Run Molecule tests for tbls scenario
    cmds:
      - molecule test -s tbls
      - task: notify
  the_silver_searcher:
    desc: Run Molecule tests for the_silver_searcher scenario
    cmds:
      - molecule test -s the_silver_searcher
      - task: notify
  tig:
    desc: Run Molecule tests for tig scenario
    cmds:
      - molecule test -s tig
      - task: notify
  tldr:
    desc: Run Molecule tests for tldr scenario
    cmds:
      - molecule test -s tldr
      - task: notify
  tree:
    desc: Run Molecule tests for tree scenario
    cmds:
      - molecule test -s tree
      - task: notify
  xmllint:
    desc: Run Molecule tests for tree scenario
    cmds:
      - molecule test -s xmllint
      - task: notify
  zns:
    desc: Run Molecule tests for zns scenario
    cmds:
      - molecule test -s zns
      - task: notify
  zx:
    desc: Run Molecule tests for zx scenario
    cmds:
      - molecule test -s zx
      - task: notify
  all-scenarios:
    desc: Run Molecule tests for all scenarios (sequential)
    cmds:
      - task: assh
      - task: bat
      - task: bottom
      - task: codex
      - task: d2
      - task: delta
      - task: diff-pdf
      - task: direnv
      - task: drawio
      - task: duckdb
      - task: eza
      - task: fd
      - task: fnt
      - task: gitleaks
      - task: github-cli
      - task: git-flow
      - task: glow
      - task: goaccess
      - task: graphviz
      - task: httpie
      - task: jc
      - task: lazydocker
      - task: lazygit
      - task: lnav
      - task: mecab
      - task: mermaid-cli
      - task: nkf
      - task: ni
      - task: osv-scanner
      - task: pandoc
      - task: pict
      - task: plantuml
      - task: poppler-utils
      - task: rclone
      - task: restic
      - task: ripgrep
      - task: runn
      - task: s3fs
      - task: task
      - task: tbls
      - task: the_silver_searcher
      - task: tig
      - task: tldr
      - task: tree
      - task: xmllint
      - task: zns
      - task: zx
      - task: default
      - task: all
      - task: notify:all
