---
- name: Set package file variable
  ansible.builtin.set_fact:
    delta_package_file: git-delta-musl_{{ delta_version }}_amd64.deb
  when: ansible_facts['architecture'] != 'aarch64'
- name: Set package file variable
  ansible.builtin.set_fact:
    delta_package_file: git-delta_{{ delta_version }}_arm64.deb
  when: ansible_facts['architecture'] == 'aarch64'
- name: Install delta
  ansible.builtin.apt:
    deb: https://github.com/{{ tools_delta_repo }}/releases/download/{{ delta_version }}/{{ delta_package_file }}
