---
- name: Install tool
  ansible.builtin.include_tasks:
    file: "{{ item }}"
  when: (item | basename)[0:-4] in install_tools
  loop: "{{ lookup('fileglob', 'tasks/package/*.yml', wantlist=True) }}"
