---
- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto
  when: ansible_facts.packages is undefined
- name: Install jc dependency for lindera
  ansible.builtin.include_tasks:
    file: package/jc.yml
  when: ansible_facts.packages['jc'] is undefined
