---
- name: Check npm command
  ansible.builtin.stat:
    path: /usr/bin/npm
  register: npm_stat_result
- name: Install node.js
  ansible.builtin.import_role:
    name: nodejs
  when: not npm_stat_result.stat.exists
