---
install_tools:
  ## https://github.com/eza-community/eza
  - eza
  ## https://graphviz.org/
  - graphviz
  ## https://github.com/sharkdp/fd
  - fd
  ## https://github.com/sharkdp/bat
  - bat
  ## https://jonas.github.io/tig/
  - tig
  ## https://github.com/jesseduffield/lazygit
  - lazygit
  ## https://goaccess.io/
  - goaccess
  ## https://github.com/google/osv-scanner
  - osv-scanner
  # https://direnv.net/
  - direnv
  ## https://github.com/jgm/pandoc
  - pandoc
  ## https://plantuml.com/ja/
  - plantuml
  ## https://github.com/k1LoW/tbls
  - tbls
  ## https://github.com/k1LoW/runn
  - runn
  ## https://github.com/dandavison/delta
  - delta
  ## https://github.com/terrastruct/d2
  - d2
  ## https://github.com/charmbracelet/glow
  - glow
  ## https://wp-cli.org/ja/
  - wp-cli
  ## https://github.com/microsoft/pict
  - pict
  # https://github.com/alexmyczko/fnt
  - fnt
  ## PDF 向けユーティリティ
  - poppler-utils
  # https://github.com/gohugoio/hugo
  - hugo
  ## https://github.com/tesseract-ocr/tesseract
  - tesseract-ocr
  ## https://taku910.github.io/mecab/
  - mecab
  ## https://github.com/google/zx
  - zx

goaccess_maxmind_account:
  account_id: "{{ lookup('env', 'MAXMIND_ACCOUNT_ID') }}"
  license_key: "{{ lookup('env', 'MAXMIND_LICENSE_KEY') }}"
