---
- name: Install add repository dependency packages
  ansible.builtin.apt:
    name: "{{ tools_add_repository_dependency_packages }}"
- name: Add backports repository
  ansible.builtin.deb822_repository:
    name: backports
    uris: http://deb.debian.org/debian
    suites: "{{ ansible_facts.distribution_release }}-backports"
    components: main
    enabled: true
    state: present
  register: apt_repository_result
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  when: apt_repository_result is changed
