---
- name: Verify
  hosts: all
  gather_facts: true
  become: true
  tasks:
    ## テストの前処理
    - name: Gather facts
      block:
        - name: Gather package facts
          ansible.builtin.package_facts:
            manager: auto
        - name: Gather service facts
          ansible.builtin.service_facts:
        - name: Gather facts on listening ports
          community.general.listen_ports_facts:
            command: ss
        - name: Set assert variables
          ansible.builtin.set_fact:
            listen_tcp_posts: "{{ ansible_facts.tcp_listen | map(attribute='port') | unique | sort | list }}"
            listen_udp_posts: "{{ ansible_facts.udp_listen | map(attribute='port') | unique | sort | list }}"
    ## direnv
    - name: Assert direnv
      ansible.builtin.assert:
        that:
          - ansible_facts.packages['direnv']
    ## bat
    - name: Assert bat
      ansible.builtin.assert:
        that:
          - ansible_facts.packages['bat']
    ## fd
    - name: Assert fd
      ansible.builtin.assert:
        that:
          - ansible_facts.packages['fd-find']
    ## tbls
    - name: Assert tbls
      ansible.builtin.assert:
        that:
          - ansible_facts.packages['tbls']
    ## runn
    - name: Assert runn
      ansible.builtin.assert:
        that:
          - ansible_facts.packages['runn']
    ## delta
    - name: Test delta
      block:
        - name: Assert delta
          ansible.builtin.assert:
            that:
              - ansible_facts.packages['git-delta-musl']
          when: ansible_facts.distribution_major_version is version('11', '<=')
        - name: Assert delta
          ansible.builtin.assert:
            that:
              - ansible_facts.packages['git-delta']
          when: ansible_facts.distribution_major_version is version('11', '>')
    ## D2
    - name: Test D2
      block:
        - name: Check installd d2
          ansible.builtin.stat:
            path: /usr/local/bin/d2
          register: d2_result
        - name: Assert d2
          ansible.builtin.assert:
            that:
              - d2_result.stat.exists
              - d2_result.stat.executable
    ## osv-scanner
    - name: Test osv-scanner
      block:
        - name: Check installd osv-scanner
          ansible.builtin.stat:
            path: /usr/local/bin/osv-scanner
          register: osv_scanner_result
        - name: Assert osv-scanner
          ansible.builtin.assert:
            that:
              - osv_scanner_result.stat.exists
              - osv_scanner_result.stat.executable
    ## glow
    - name: Assert glow
      ansible.builtin.assert:
        that:
          - ansible_facts.packages['glow']
    ## graphviz
    - name: Assert graphviz
      ansible.builtin.assert:
        that:
          - ansible_facts.packages['graphviz']
    ## wp-cli
    - name: Check installd wp-cli
      ansible.builtin.stat:
        path: /usr/local/bin/wp
      register: wp_result
    - name: Assert wp-cli
      ansible.builtin.assert:
        that:
          - wp_result.stat.exists
          - wp_result.stat.executable
    ## pict
    - name: Check installd pict
      ansible.builtin.stat:
        path: /usr/local/bin/pict
      register: pict_result
    - name: Assert pict
      ansible.builtin.assert:
        that:
          - pict_result.stat.exists
          - pict_result.stat.executable
    ## Hugo
    - name: Test Hogo
      block:
        - name: Check hogo
          ansible.builtin.stat:
            path: /usr/local/bin/hugo
          register: hugo_result
        - name: Assert hogo
          ansible.builtin.assert:
            that:
              - hugo_result.stat.exists
              - hugo_result.stat.executable
    ## plantuml
    - name: Assert Plantuml
      ansible.builtin.assert:
        that:
          - ansible_facts.packages['plantuml']
    ## tesseract-ocr
    - name: Assert tesseract-ocr
      ansible.builtin.assert:
        that:
          - ansible_facts.packages['tesseract-ocr']
    ## poppler-utils
    - name: Assert poppler-utils
      ansible.builtin.assert:
        that:
          - ansible_facts.packages['poppler-utils']
    ## pandoc
    - name: Assert pandoc
      ansible.builtin.assert:
        that:
          - ansible_facts.packages['pandoc']
    ## mecab
    - name: Assert mecab
      ansible.builtin.assert:
        that:
          - ansible_facts.packages['mecab']
    ## fnt
    - name: Assert fnt
      ansible.builtin.assert:
        that:
          - ansible_facts.packages['fnt']
    ## zx
    - name: Test zx
      block:
        - name: Check installd zx
          ansible.builtin.stat:
            path: /usr/bin/zx
          register: zx_result
        - name: Assert zx command
          ansible.builtin.assert:
            that:
              - zx_result.stat.exists
              - zx_result.stat.executable
