---
- name: Set package file variable
  ansible.builtin.set_fact:
    delta_package_file: git-delta_{{ delta_version }}_{{ architecture_files[ansible_facts['architecture']] }}.deb
  vars:
    architecture_files:
      x86_64: amd64
