---
- name: Add apt signing key
  ansible.builtin.get_url:
    url: "{{ tools_eza_apt_key_url }}"
    dest: "{{ tools_eza_apt_key_dest }}"
    mode: "0644"
- name: Add notesalexp repository
  ansible.builtin.apt_repository:
    filename: gierens
    repo: >
      deb [signed-by={{ tools_eza_apt_key_dest }}]
      http://deb.gierens.de
      stable
      main
    state: present
