---
## @see https://github.com/eza-community/eza/blob/main/INSTALL.md
- name: Create GPG key directory
  ansible.builtin.file:
    path: "{{ tools_eza_apt_key_dest | dirname }}"
    state: directory
    mode: "0755"
- name: Download GPG key
  ansible.builtin.get_url:
    url: "{{ tools_eza_apt_key_url }}"
    dest: "{{ tools_eza_apt_key_download_dest }}"
    mode: "0644"
  register: gpg_key_download_result
- name: Convert GPG key
  ansible.builtin.command:
    cmd: gpg --dearmor -o {{ tools_eza_apt_key_dest }} {{ tools_eza_apt_key_download_dest }}
  when: gpg_key_download_result is changed
- name: Add gierens repository
  ansible.builtin.deb822_repository:
    name: gierens
    uris: http://deb.gierens.de
    suites: stable
    components: main
    signed_by: "{{ tools_eza_apt_key_dest }}"
    enabled: true
    state: present
  register: apt_repository_result
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  when: apt_repository_result is changed
