---
## @see https://goaccess.io/download#official-repo
- name: Add apt signing key
  ansible.builtin.get_url:
    url: "{{ tools_goaccess_apt_key_url }}"
    dest: "{{ tools_goaccess_apt_key_dest }}"
    mode: "0644"
- name: Add goaccess repository
  ansible.builtin.apt_repository:
    filename: goaccess
    repo: >
      deb [signed-by={{ tools_goaccess_apt_key_dest }} arch={{ arch_type_maps[ansible_facts.architecture] }}]
      https://deb.goaccess.io/
      {{ ansible_facts.distribution_release }}
      main
    state: present
  vars:
    arch_type_maps:
      x86_64: amd64
      aarch64: arm64
