---
- name: Install pipx
  ansible.builtin.apt:
    name: pipx
    default_release: "{{ ansible_facts.distribution_release }}-backports"
- name: Install litecli
  community.general.pipx:
    name: litecli
  become: false
