---
- name: Verify
  hosts: all
  gather_facts: true
  become: true
  tasks:
    ## テストの前処理
    - name: Gather facts
      block:
        - name: Gather package fact
          ansible.builtin.package_facts:
            manager: auto
          when: ansible_facts.packages is undefined
        - name: Gather service fact
          ansible.builtin.service_facts:
          when: ansible_facts.services is undefined
        - name: Gather listening ports fact
          community.general.listen_ports_facts:
            command: ss
          when: ansible_facts.tcp_listen is undefined or ansible_facts.udp_listen is undefined
        - name: Set listen ports fact variables
          ansible.builtin.set_fact:
            listen_tcp_posts: "{{ ansible_facts.tcp_listen | map(attribute='port') | unique | sort | list }}"
            listen_udp_posts: "{{ ansible_facts.udp_listen | map(attribute='port') | unique | sort | list }}"
    - name: Find variable file
      ansible.builtin.set_fact:
        variable_file: "{{ lookup('first_found', params, errors='ignore') }}"
      vars:
        params:
          files:
            - "{{ lookup('env', 'MOLECULE_SCENARIO_DIRECTORY') }}/group_vars/all.yml"
    - name: Include variable file
      ansible.builtin.include_vars:
        file: "{{ variable_file }}"
      when: variable_file | length > 0
    - name: Execute tool test
      ansible.builtin.include_tasks:
        file: ../_common/tests/{{ tool_name }}.yml
      loop:
        - "{{ lookup('env', 'MOLECULE_SCENARIO_DIRECTORY') | basename }}"
      loop_control:
        loop_var: tool_name
        label: "{{ tool_name }}"
