---
- name: Set Install version variable
  when: d2_version == 'latest'
  block:
    - name: Get latest version
      ansible.builtin.include_tasks:
        file: package/common/get_latest_version.yml
      vars:
        github_repo: "{{ tools_d2_repo }}"
    - name: Set package version
      ansible.builtin.set_fact:
        d2_version: "{{ latest_version }}"
- name: Set download file variable
  ansible.builtin.set_fact:
    d2_download_file: d2-{{ d2_version }}-{{ ansible_facts['system'] | lower }}-{{ arch_type_maps[ansible_facts['architecture']] }}.tar.gz
  vars:
    arch_type_maps:
      x86_64: amd64
      aarch64: arm64
- name: Create download directory
  ansible.builtin.file:
    path: /usr/local/src/d2
    state: directory
    mode: "0755"
- name: Download d2
  ansible.builtin.unarchive:
    src: https://github.com/{{ tools_d2_repo }}/releases/download/{{ d2_version }}/{{ d2_download_file }}
    dest: /usr/local/src/d2
    extra_opts:
      - --strip-components=1
    remote_src: true
  register: d2_unarchive_result
- name: Install/update d2
  ansible.builtin.command:
    cmd: /usr/local/src/d2/scripts/install.sh
    chdir: /usr/local/src/d2
  when: d2_unarchive_result is changed
