---
- name: Set Install version variable
  when: glow_version == 'latest'
  block:
    - name: Set Github API request header
      ansible.builtin.set_fact:
        github_api_request_headers:
          Accept: application/vnd.github+json
    - name: Merge Github API Authorization request header
      ansible.builtin.set_fact:
        github_api_request_headers: "{{ github_api_request_headers | combine(merge_reauest_header) }}"
      vars:
        merge_reauest_header:
          Authorization: Bearer {{ lookup('env', 'GITHUB_TOKEN') }}
      when: lookup('env', 'GITHUB_TOKEN') | length > 0
    - name: Get latest release
      ansible.builtin.uri:
        url: https://api.github.com/repos/{{ tools_glow_repo }}/releases/latest
        headers: "{{ github_api_request_headers }}"
      register: latest_releases
    - name: Set version variable
      ansible.builtin.set_fact:
        glow_version: "{{ latest_releases.json.tag_name }}"
- name: Set package file variable
  ansible.builtin.set_fact:
    package_file: glow_{{ glow_version[1:] }}_{{ arch_type_maps[ansible_facts['architecture']] }}.deb
  vars:
    arch_type_maps:
      x86_64: amd64
      aarch64: arm64
- name: Install glow
  ansible.builtin.apt:
    deb: https://github.com/{{ tools_glow_repo }}/releases/download/{{ glow_version }}/{{ package_file }}
