---
- name: Set Install version variable
  when: glow_version == 'latest'
  block:
    - name: Get latest version
      ansible.builtin.include_tasks:
        file: package/common/get_latest_version.yml
      vars:
        github_repo: "{{ tools_glow_repo }}"
    - name: Set package version
      ansible.builtin.set_fact:
        glow_version: "{{ latest_version }}"
- name: Set package file variable
  ansible.builtin.set_fact:
    package_file: glow_{{ glow_version[1:] }}_{{ arch_type_maps[ansible_facts['architecture']] }}.deb
  vars:
    arch_type_maps:
      x86_64: amd64
      aarch64: arm64
- name: Install glow
  ansible.builtin.apt:
    deb: https://github.com/{{ tools_glow_repo }}/releases/download/{{ glow_version }}/{{ package_file }}
