---
- name: Install goaccess
  ansible.builtin.apt:
    name: goaccess
- name: Install geoipupdate dependency packages
  when:
    - goaccess_maxmind_account.account_id | length > 0
    - goaccess_maxmind_account.license_key | length > 0
  block:
    - name: Install cron package
      ansible.builtin.apt:
        name: cron
    - name: Get latest version
      ansible.builtin.include_tasks:
        file: common/get_latest_version.yml
      vars:
        github_repo: maxmind/geoipupdate
        target_name: geoipupdate
    - name: Set package version
      ansible.builtin.set_fact:
        geoipupdate_version: "{{ latest_version }}"
    - name: Set package file name parts variables
      ansible.builtin.set_fact:
        asset_file_version: "{{ geoipupdate_version[1:] }}"
        asset_file_system: "{{ ansible_facts['system'] | lower }}"
        asset_file_arch: "{{ arch_type_maps[ansible_facts['architecture']] }}"
      vars:
        arch_type_maps:
          x86_64: amd64
          aarch64: arm64
    - name: Set variable
      ansible.builtin.set_fact:
        asset_file: geoipupdate_{{ asset_file_version }}_{{ asset_file_system }}_{{ asset_file_arch }}.deb
    - name: Install geoipupdate
      ansible.builtin.apt:
        deb: https://github.com/maxmind/geoipupdate/releases/download/{{ geoipupdate_version }}/{{ asset_file }}
