---
- name: Set Install version variable
  when: hugo_version == 'latest'
  block:
    - name: Set Github API request header
      ansible.builtin.set_fact:
        github_api_request_headers:
          Accept: application/vnd.github+json
    - name: Merge Github API Authorization request header
      ansible.builtin.set_fact:
        github_api_request_headers: "{{ github_api_request_headers | combine(merge_reauest_header) }}"
      vars:
        merge_reauest_header:
          Authorization: Bearer {{ lookup('env', 'GITHUB_TOKEN') }}
      when: lookup('env', 'GITHUB_TOKEN') | length > 0
    - name: Get latest release
      ansible.builtin.uri:
        url: https://api.github.com/repos/{{ tools_hugo_repo }}/releases/latest
        headers: "{{ github_api_request_headers }}"
      register: latest_releases
    - name: Set version variable
      ansible.builtin.set_fact:
        hugo_version: "{{ latest_releases.json.tag_name }}"
- name: Set package file variable
  ansible.builtin.set_fact:
    package_file: "{{ asset_file_prefix }}_{{ hugo_version[1:] }}_linux-{{ arch_type_maps[ansible_facts['architecture']] }}.deb"
  vars:
    asset_file_prefix: "{{ 'hugo_extended' if hugo_extended else 'hugo' }}"
    arch_type_maps:
      x86_64: amd64
      aarch64: arm64
- name: Install Hugo
  ansible.builtin.apt:
    deb: https://github.com/{{ tools_hugo_repo }}/releases/download/{{ hugo_version }}/{{ package_file }}
