---
- name: Set Install version variable
  when: hugo_version == 'latest'
  block:
    - name: Get latest version
      ansible.builtin.include_tasks:
        file: package/common/get_latest_version.yml
      vars:
        github_repo: "{{ tools_hugo_repo }}"
    - name: Set package version
      ansible.builtin.set_fact:
        hugo_version: "{{ latest_version }}"
- name: Set package file variable
  ansible.builtin.set_fact:
    package_file: "{{ asset_file_prefix }}_{{ hugo_version[1:] }}_linux-{{ arch_type_maps[ansible_facts['architecture']] }}.deb"
  vars:
    asset_file_prefix: "{{ 'hugo_extended' if hugo_extended else 'hugo' }}"
    arch_type_maps:
      x86_64: amd64
      aarch64: arm64
- name: Install hugo
  ansible.builtin.apt:
    deb: https://github.com/{{ tools_hugo_repo }}/releases/download/{{ hugo_version }}/{{ package_file }}
