---
- name: Get latest release
  when: jc_version | default('latest') == 'latest'
  block:
    - name: Get latest version
      ansible.builtin.include_tasks:
        file: common/get_latest_version.yml
      vars:
        github_repo: "{{ tools_jc_repo }}"
        target_name: jc
    - name: Set package version
      ansible.builtin.set_fact:
        jc_version: "{{ latest_version }}"
- name: Set variable
  ansible.builtin.set_fact:
    package_file: jc_{{ jc_version[1:] }}-1_{{ arch_type_maps[ansible_facts['architecture']] }}.deb
  vars:
    arch_type_maps:
      x86_64: amd64
      aarch64: arm64
- name: Install jc
  ansible.builtin.apt:
    deb: https://github.com/{{ tools_jc_repo }}/releases/download/{{ jc_version }}/{{ package_file }}
