---
- name: Set Install version variable
  when: mailpit_version == 'latest'
  block:
    - name: Get latest version
      ansible.builtin.uri:
        url: https://api.github.com/repos/{{ tools_mailpit_repo }}/releases/latest
        headers:
          Accept: application/vnd.github+json
      register: latest_releases
    - name: Set version variable
      ansible.builtin.set_fact:
        mailpit_version: "{{ latest_releases.json.tag_name }}"
- name: Set download file variable
  ansible.builtin.set_fact:
    mailpit_download_file: mailpit-{{ ansible_facts['system'] | lower }}-{{ architecture_types[ansible_facts['architecture']] }}.tar.gz
  vars:
    architecture_types:
      x86_64: amd64
      aarch64: arm64
- name: Install mailpit
  ansible.builtin.unarchive:
    src: https://github.com/{{ tools_mailpit_repo }}/releases/download/{{ mailpit_version }}/{{ mailpit_download_file }}
    dest: /usr/local/bin
    include:
      - mailpit
    remote_src: true
