---
- name: Install mermaid-cli
  community.general.npm:
    name: "@mermaid-js/mermaid-cli"
    global: true
    state: "{{ mermaid_cli_latest_install | default(false) | ternary('latest', 'present') }}"
