---
- name: Set Install version variable
  when: osv_scanner_version == 'latest'
  block:
    - name: Get latest version
      ansible.builtin.include_tasks:
        file: package/common/get_latest_version.yml
      vars:
        github_repo: "{{ tools_osv_scanner_repo }}"
    - name: Set package version
      ansible.builtin.set_fact:
        osv_scanner_version: "{{ latest_version }}"
- name: Set download file variable
  ansible.builtin.set_fact:
    osv_scanner_architecture_type: "{{ arch_type_maps[ansible_facts['architecture']] }}"
  vars:
    arch_type_maps:
      x86_64: amd64
      aarch64: arm64
- name: Set download file name
  ansible.builtin.set_fact:
    osv_scanner_download_file: osv-scanner_{{ ansible_facts['system'] | lower }}_{{ osv_scanner_architecture_type }}
- name: Install osv-scanner
  ansible.builtin.get_url:
    url: https://github.com/{{ tools_osv_scanner_repo }}/releases/download/{{ osv_scanner_version }}/{{ osv_scanner_download_file }}
    dest: /usr/local/bin/osv-scanner
    mode: "0755"
