---
- name: Set Install version variable
  when: osv_scanner_version == 'latest'
  block:
    - name: Get osv-scanner latest version
      ansible.builtin.uri:
        url: https://api.github.com/repos/{{ tools_osv_scanner_repo }}/releases/latest
        headers:
          Accept: application/vnd.github+json
      register: latest_releases
    - name: Set version variable
      ansible.builtin.set_fact:
        osv_scanner_version: "{{ latest_releases.json.tag_name }}"
- name: Set download file variable
  ansible.builtin.set_fact:
    osv_scanner_architecture_type: "{{ architecture_types[ansible_facts['architecture']] }}"
  vars:
    architecture_types:
      x86_64: amd64
      aarch64: arm64
- name: Set download file name
  ansible.builtin.set_fact:
    osv_scanner_download_file: osv-scanner_{{ ansible_facts['system'] | lower }}_{{ osv_scanner_architecture_type }}
- name: Install osv-scanner
  ansible.builtin.get_url:
    url: https://github.com/{{ tools_osv_scanner_repo }}/releases/download/{{ osv_scanner_version }}/{{ osv_scanner_download_file }}
    dest: /usr/local/bin/osv-scanner
    mode: "0755"
