---
- name: Set Install version variable
  when: pandoc_version == 'latest'
  block:
    - name: Get latest version
      ansible.builtin.include_tasks:
        file: common/get_latest_version.yml
      vars:
        github_repo: "{{ tools_pandoc_repo }}"
        target_name: pandoc
    - name: Set package version
      ansible.builtin.set_fact:
        pandoc_version: "{{ latest_version }}"
- name: Set package file variable
  ansible.builtin.set_fact:
    package_file: pandoc-{{ pandoc_version }}-1-{{ arch_type_maps[ansible_facts['architecture']] }}.deb
  vars:
    arch_type_maps:
      x86_64: amd64
      aarch64: arm64
- name: Install pandoc
  ansible.builtin.apt:
    deb: https://github.com/{{ tools_pandoc_repo }}/releases/download/{{ pandoc_version }}/{{ package_file }}
