---
- name: Set Install version variable
  when: pandoc_version == 'latest'
  block:
    - name: Get latest release
      ansible.builtin.uri:
        url: https://api.github.com/repos/{{ tools_pandoc_repo }}/releases/latest
        headers:
          Accept: application/vnd.github+json
      register: latest_releases
    - name: Set version variable
      ansible.builtin.set_fact:
        pandoc_version: "{{ latest_releases.json.tag_name }}"
- name: Set package file variable
  ansible.builtin.set_fact:
    package_file: pandoc-{{ pandoc_version }}-1-{{ architecture_files[ansible_facts['architecture']] }}.deb
  vars:
    architecture_files:
      x86_64: amd64
- name: Install pandoc
  ansible.builtin.apt:
    deb: https://github.com/{{ tools_pandoc_repo }}/releases/download/{{ pandoc_version }}/{{ package_file }}
