---
- name: Checkout pict source
  ansible.builtin.git:
    repo: https://github.com/{{ tools_pict_repo }}.git
    dest: /usr/local/src/pict
    version: main
  register: checkout_result
- name: Build binary
  ansible.builtin.command:
    cmd: make
    chdir: /usr/local/src/pict
  when: checkout_result is changed
- name: Create symlink
  ansible.builtin.file:
    src: /usr/local/src/pict/pict
    dest: /usr/local/bin/pict
    state: link
