---
- name: Set Install version variable
  when: runn_version == 'latest'
  block:
    - name: Get latest release
      ansible.builtin.uri:
        url: https://api.github.com/repos/{{ tools_runn_repo }}/releases/latest
        headers:
          Accept: application/vnd.github+json
      register: latest_releases
    - name: Set version variable
      ansible.builtin.set_fact:
        runn_version: "{{ latest_releases.json.tag_name }}"
- name: Set pckage file variable
  ansible.builtin.set_fact:
    package_file: runn_{{ runn_version[1:] }}-1_{{ architecture_files[ansible_facts['architecture']] }}.deb
  vars:
    architecture_files:
      x86_64: amd64
- name: Install runn
  ansible.builtin.apt:
    deb: https://github.com/{{ tools_runn_repo }}/releases/download/{{ runn_version }}/{{ package_file }}
