---
- name: Set Install version variable
  when: task_version == 'latest'
  block:
    - name: Get latest version
      ansible.builtin.include_tasks:
        file: package/common/get_latest_version.yml
      vars:
        github_repo: "{{ tools_task_repo }}"
    - name: Set package version
      ansible.builtin.set_fact:
        task_version: "{{ latest_version }}"
- name: Set package file variable
  ansible.builtin.set_fact:
    package_file: task_{{ ansible_facts['system'] | lower }}_{{ arch_type_maps[ansible_facts['architecture']] }}.deb
  vars:
    arch_type_maps:
      x86_64: amd64
      aarch64: arm64
- name: Install bat
  ansible.builtin.apt:
    deb: https://github.com/{{ tools_task_repo }}/releases/download/{{ task_version }}/{{ package_file }}
