---
- name: Set Install version variable
  when: tbls_version == 'latest'
  block:
    - name: Get latest version
      ansible.builtin.include_tasks:
        file: common/get_latest_version.yml
      vars:
        github_repo: "{{ tools_tbls_repo }}"
    - name: Set package version
      ansible.builtin.set_fact:
        tbls_version: "{{ latest_version }}"
- name: Set package file variable
  ansible.builtin.set_fact:
    package_file: tbls_{{ tbls_version[1:] }}-1_{{ arch_type_maps[ansible_facts['architecture']] }}.deb
  vars:
    arch_type_maps:
      x86_64: amd64
      aarch64: arm64
- name: Install tbls
  ansible.builtin.apt:
    deb: https://github.com/{{ tools_tbls_repo }}/releases/download/{{ tbls_version }}/{{ package_file }}
