---
- name: Set Install version variable
  when: uv_version == 'latest'
  block:
    - name: Get latest version
      ansible.builtin.include_tasks:
        file: common/get_latest_version.yml
      vars:
        github_repo: "{{ tools_uv_repo }}"
        target_name: uv
    - name: Set package version
      ansible.builtin.set_fact:
        uv_version: "{{ latest_version }}"
- name: Set asset file name
  ansible.builtin.set_fact:
    asset_file: uv-{{ ansible_facts['architecture'] }}-unknown-linux-gnu.tar.gz
- name: Install uv
  ansible.builtin.unarchive:
    src: https://github.com/{{ tools_uv_repo }}/releases/download/{{ uv_version }}/{{ asset_file }}
    dest: /usr/local/bin
    extra_opts:
      - --strip-components=1
    remote_src: true
